### ISSUE TITLE
[Bug]: Flat, Round, Chance params in stats

### ISSUE THREAD

**Issue by 3Lord3** [magemonkeystudio/divinity#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created item generator with 1-2 stats (Durability 100% and Mana_regen 50% (1-10)) with Flat Range and Round. Flat range and/or rounding does not work. Durability appears, but mana_regen appears VERY rarely (Two out of a hundred!) even if I set the chance to 99.9%. If I set at least 2 stats, then mana regen will always be

### Expected Behavior

Flat Range and Round work, stat chances work correctly

### Steps To Reproduce

1. Create item generator
2. Add 1-2 stats (Durability 100% + some stat any%) with Flat Range and Round
3. Disable other stats
4. Check generated items

### Environment

```markdown
- Server Software: Purpur 1.20.6-2227-79d199c (MC: 1.20.6)*
- Divinity Version: 1.0.0-R0.17-SNAPSHOT
- Codex Version: 1.0.0-R0.17-SNAPSHOT
- Plugins: Paper Plugins: (3): Codex, Divinity, Fabled | Bukkit Plugins: (1): PlaceholderAPI, ProtocolLib, spark
```

### Anything else?

[uncommon_staff.txt](https://github.com/user-attachments/files/15818527/uncommon_staff.txt)

**Comment by goflishMC** [comment]
It's not really a bug, the code was just never finished for defense and item stats.

It only works for Damage Types right now. I have a issue already opened to add it to armor. I'll get it put on the list for item stats, but not sure about ETA, could be a few weeks. We have a lot already that we are working on.

**Comment by Travja** [comment]
I'm implementing some code here that makes stats actually function properly with the round setting. This doesn't, however, make these stats able to have a range. Most of these stats (mana, durability, armor toughness, etc.) can't have variable values as each time they're applied, it would have to pick a different value. That being said, flat range is effectively ignored for these stats. Defense on the other hand, could potentially have the flat range added, but as of right now, defense is not a ranged stat and would take some decent refactoring to do. That, I would classify as more of an enhancement rather than a bug and would be a separate issue.
